export enum EntityName {
  User = "user",
  Profile = "profile",
  Otp = "otp",
  Category = "category",
  Product = "product",
  ProductColor = "product_color",
  ProductSize = "product_size",
  ProductDetail = "product_detail",
  ProductImage = "product_image",
  Basket = "basket",
  Order = "order",
  OrderItems = "order_items",
  Payment = "payment",
  Discount = "discount",
  Blog = "blog",
  BlogCategory = "blog_category",
  BlogLikes = "blog_likes",
  BlogComments = "blog_comments",
  BlogBookmark = "blog_bookmarks",
  BlogTag = "tags",
  BlogTags = "blog_tag",
  Address = "address",
  SupportTicket = "support_ticket",
  SupportMessage = "support_message",
  Role = "role",
  Permission = "permission",
}
